config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'items#index'

  resources :items, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resource :profile, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  validates :price, presence: true
  validates :category, presence: true
  validates :item_name, presence: true
  validates :description, presence: true

  CATEGORY = ["Véhicule", "Jouet", "Multimédia", "Immobilier", "Décoration"]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :items
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number, presence: true
  validates :civility, presence: true
  validates :address, presence: true
  validates :post_code, presence: true
  validates :city, presence: true
  validates :country, presence: true
  validates :status, presence: true

  def self.array_city
    users = User.all
    users.map do |user|
      user_city = user.city
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/item_controller.rb
class ItemController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    @item = current_user.items.new(item_params)
    if @item.save
      redirect_to profile_path
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to profile_path*
    else
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to profile_path
  end

  private
  def item_params
    params.require(:item).permit(:price, :category, :item_name, :description, :picture, :user_id)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    if params[:category] == nil
      @items = Item.all
    else
      items_filter = ItemFilter.new(params)
      items_filter.filter
      @items = items_filter.items
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def new
    @item = Item.new
  end

  def create
    @item = current_user.items.new(item_params)
    if @item.save
      redirect_to profile_path
    else
      render :new
    end
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to profile_path
    else
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to profile_path
  end

  private
  def item_params
    params.require(:item).permit(:price, :category, :item_name, :description, :picture, :user_id)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @items = current_user.items
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/items/_form.html.erb
<%= simple_form_for(@item) do |f| %>
  <%= f.error_notification %>
  <%= f.input :category, collection: Item::CATEGORY %>
  <%= f.input :item_name %>
  <%= f.text_area :description %>
  <%= f.input :price %>
  <%= f.button :submit , class: "btn btn-primary"  %>
<% end %>

app/views/items/create.html.erb
<h1>Item#create</h1>
<p>Find me in app/views/item/create.html.erb</p>

app/views/items/destroy.html.erb
<h1>Item#destroy</h1>
<p>Find me in app/views/item/destroy.html.erb</p>

app/views/items/edit.html.erb
<%= render 'form' %>

app/views/items/index.html.erb
<%= render 'shared/search_bar' %>
<%= link_to "tout les objets en vente", items_path, class: "btn btn-primary" %>
<% if user_signed_in? %>
  <div class="btn btn-primary">
    <%= link_to "vos objets", profile_path %>
  </div>
<% else %>
  <button class="btn btn-primary"><%= link_to "connexion", new_user_session_path %></button>
<% end %>
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <% @items.each do |item| %>
        <div class="card">
          <% if item.picture == nil %>
            <p>pas de photo pour cet article</p>
          <% else %>
            <%= image_tag item.picture %>
          <% end %>
          <h4><%= item.item_name %></h4>
          <h5><%= item.category %></h5>
          <h3><%= item.price %></h3>
          <p><%= item.description %></p>
        </div>
        <div class="btn btn-primary">
          <%= link_to "en savoir plus", item_path(item) %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<%= render 'form' %>

app/views/items/show.html.erb
<h1><%= @item.item_name %></h1>
<% if item.picture == nil %>
  <p>pas de photo pour cet article</p>
<% else %>
  <%= image_tag item.picture %>
<% end %>
<h3><%= @item.price %></h3>
<p><%= @item.description %></p>

<% if user_signed_in? %>
  <h5><%= @item.user.phone_number %></h5>
  <h5><%= @item.user.email %></h5>
<% else %>
  <button class="btn btn-primary"><%= link_to "voir les infos du vendeur", new_user_session_path %></button>
<% end %>

app/views/items/update.html.erb
<h1>Item#update</h1>
<p>Find me in app/views/item/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestLeBoncoin</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/profiles/show.html.erb
<button class="btn btn-primary"><%= link_to "mettre un objet en vente ?", new_item_path %></button>
<%= link_to "accueil", items_path, class: "btn btn-primary" %>

<h2>Vos objets en vente</h2>
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <% @items.each do |item| %>
        <div class="card">
        <% if item.picture == nil %>
          <p>pas de photo pour cet article</p>
        <% else %>
          <%= image_tag item.picture %>
        <% end %>
          <h4><%= item.item_name %></h4>
          <h3><%= item.price %>€</h3>
          <p><%= item.description %></p>
        </div>
        <div><%= link_to "supprimer", item_path(item), method: :delete, data: { confirm: 'voulez-vous supprimer cet objet?'} %>
        <div><%= link_to "modifier cet objet", edit_item_path(item) %></div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_search_bar.html.erb
<h2>recherche</h2>
<div class="row">
  <%= form_tag("/items", method: "get")  do%>

    <div class="col-xs-12 col-md-2">
      <%= text_field_tag(:item_name, nil, required: false, placeholder: "ex renault clio 3") %>
    </div>

    <div class="col-xs-12 col-md-1">
      <%= select_tag :category, options_for_select(Item::CATEGORY) %>
    </div>

    <div class="col-xs-12 col-md-1">
      <%= select_tag :city, options_for_select(User.array_city)%>
    </div>

    <div class="col-xs-12 col-md-2">
      <%= text_field_tag(:min_price, nil, placeholder: "30") %>€
    </div>

        <div class="col-xs-12 col-md-2">
      <%= text_field_tag(:max_price, nil, placeholder: "900") %>€
    </div>

    <div class="col-xs-12 col-md-2">
      <%= submit_tag("chercher", class: "btn btn-primary") %>
    </div>
    <% end %>
</div>